version: '3.2'
services:
  api:
    image: apiviva/bot:latest
    build: .
    container_name: apiviva
    environment:
      - ENVIRONMENT=prod
      - LINK_API_EXTERNAL=http://grupozap-code-challenge.s3-website-us-east-1.amazonaws.com/sources/source-2.json
    ports:
      - "8000:8000"
    volumes:
      - .:/code
