service: api-viva-nao-ral

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: ${opt:stage, "prod"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: api-viva-nao-real-layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - "app.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        -
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
      ENVIRONMENT: "prod"
      LINK_API_EXTERNAL: "http://grupozap-code-challenge.s3-website-us-east-1.amazonaws.com/sources/source-2.json"
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}